---

- name: Removal of swapfile entries from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disabling swap if it exists
  command: swapoff -a
  when: ansible_swaptotal_mb > 0
