---

- name: repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable Repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: yes

- name: install Docker
  yum:
    name: docker
    state: present
    update_cache: true

- name: Creating a repository file for Kubernetes
  file:
    path: /etc/yum.repos.d/kubernetes.repo
    state: touch

- name: Adding repository details in Kubernetes repo file.
  blockinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Installing required packages
  yum:
    name: "{{ packages }}"
    state: present

- name: Starting and Enabling the required services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ services }}"

- name: disable SELinux
  command: setenforce 0

- name: disable SELinux on reboot
  selinux:
    state: disabled

- name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
    state: present
    reload: yes
    ignoreerrors: yes

- name: ensure net.bridge.bridge-nf-call-iptables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present
    reload: yes
    ignoreerrors: yes

- name: Reloading system.conf
  shell: sysctl --system

- name: Add br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Reloading daemon
  command: systemctl daemon-reload

- name: Kubelet
  service:
    name: kubelet
    state: restarted
    enabled: yes
